### ISSUE TITLE
educhat-sft-002-13b-baichuan模型似乎不全

### ISSUE THREAD

**Issue by jeffersonchou** [ECNU-ICALK/EduChat#12]
少了tokenizer.model，tokenizer_config.json，tokenization_baichuan.py和special_tokens_map.json；可能还缺了added_tokens.json，config.json中的"vocab_size": 64016，跟官方64000不一致，能上传一下吗？感谢！

**Comment by sndnyang** [comment]
我试了下， 可以的

https://github.com/sndnyang/LearnIsFun/blob/master/educhat/TryEduchat-baichuan.ipynb
