### ISSUE TITLE
关于作文批改

### ISSUE THREAD

**Issue by AIRedWood** [ECNU-ICALK/EduChat#4]
作者您好：

我想尝试一下首页显示的作文批改功能。请问我应该怎么做。

我现在的情况是：下载了educhat-sft-002-7b模型并跑通了educhat_gradio.py。

但是我不知道怎么才能执行作文批改，我看你的gif图里面左下角工具图标边上显示作文批改。请问这个作文批改代表着一个特殊的prompt还是包含一些其他的工具or模型的修改在里面？

**Comment by butyuhao** [comment]
感谢对EduChat的关注，作文批改功能是开放问答功能的子功能，所以使用开放问答的system_prompt，然后提问的时候用类似于“帮我评价一下这篇作文：作文正文”的格式即可。
